# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-5.3

# Local packages, usually specified by relative directory name
packages:
  - ivory/
  - ivory-artifact/
  - ivory-backend-c/
  - ivory-eval/
  - ivory-examples/
  - ivory-hw/
  - ivory-model-check/
  - ivory-opts/
  - ivory-quickcheck/
  - ivory-serialize/
  - ivory-stdlib/

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - exception-mtl-0.4
  - ghc-srcspan-plugin-0.2.1.0
  - language-c-quote-0.11.4
  - mainland-pretty-0.4.1.2
  - symbol-0.2.4
  - hobbits-1.2.4
  - z3-4.1.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

install-ghc: true

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
extra-include-dirs: [/usr/local/include]
extra-lib-dirs: [/usr/local/lib]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
