# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, filepath, ivory, ivoryBackendC, ivoryOpts, monadLib
, prettyShow
}:

cabal.mkDerivation (self: {
  pname = "ivory-model-check";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [
    filepath ivory ivoryBackendC ivoryOpts monadLib prettyShow
  ];
  meta = {
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
