# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cmdlib, filepath, ivory, ivoryOpts, languageCQuote
, mainlandPretty, monadLib, srcloc
}:

cabal.mkDerivation (self: {
  pname = "ivory-backend-c";
  version = "0.1.0.1";
  src = ./.;
  buildDepends = [
    cmdlib filepath ivory ivoryOpts languageCQuote mainlandPretty
    monadLib srcloc
  ];
  meta = {
    homepage = "http://smaccmpilot.org/languages/ivory-introduction.html";
    description = "Ivory C backend";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
