# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ivory, monadLib, QuickCheck, random }:

cabal.mkDerivation (self: {
  pname = "ivory-quickcheck";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [ ivory monadLib QuickCheck random ];
  meta = {
    homepage = "http://smaccmpilot.org/languages/ivory-introduction.html";
    description = "QuickCheck driver for Ivory";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
