# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dlist, monadLib, parsec, thLift, alex, happy }:

cabal.mkDerivation (self: {
  pname = "ivory";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [ dlist monadLib parsec thLift ];
  buildTools = [ alex happy ];
  meta = {
    homepage = "http://smaccmpilot.org/languages/ivory-introduction.html";
    description = "Safe embedded C programming";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
