# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dlist, fgl, filepath, ivory, monadLib }:

cabal.mkDerivation (self: {
  pname = "ivory-opts";
  version = "0.1.0.1";
  src = ./.;
  buildDepends = [ dlist fgl filepath ivory monadLib ];
  meta = {
    homepage = "http://smaccmpilot.org/languages/ivory-introduction.html";
    description = "Ivory compiler optimizations";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
